from setuptools import setup, find_packages

setup(
    name='pymss',
    version='0.5',
    packages=find_packages(),
    description='Python package for music source separation.',
    long_description=open('README.md', encoding='utf-8').read(),
    long_description_content_type='text/markdown',
    url='https://github.com/KitsuneX07/pymss',
    author='KitsuneX07',
    author_email='ghast1085654218@163.com',
    license='MIT',
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'Intended Audience :: Science/Research',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
        'Programming Language :: Python :: 3.12',
        'Topic :: Multimedia :: Sound/Audio',
        'Topic :: Scientific/Engineering :: Artificial Intelligence',
        'Operating System :: OS Independent',
    ],
    keywords='music source separation, audio separation, music processing, machine learning, audio',
    python_requires='>=3.7',
    install_requires=[
        "pydub",
        "numpy",
        "torch",
        "torchaudio",
        "librosa",
        "soundfile",
        "tqdm",
        "ml-collections",
        "omegaconf",
        "pyyaml",
        "demucs",
        "colorama",
        "pytorch_lightning",
        "asteroid",
        "spafe",
        "pedalboard",
        "torch_audiomentations",
        "beartype",
        "rotary_embedding_torch",
        "transformers",
        "segmentation_models_pytorch",
    ],
    project_urls={
        'Bug Tracker': 'https://github.com/KitsuneX07/pymss/issues',
        'Source Code': 'https://github.com/KitsuneX07/pymss',
        'Documentation': 'https://github.com/KitsuneX07/pymss/blob/main/README.md',
    },
)
